name: macOS-Tailscale
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          # This matches your screenshot exactly
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Setting up the Mac
        run: source setup.sh "Aeroniscoolmc2" ""

      - name: Show Tailscale IP
        run: tailscale ip -4

      - name: Keep Alive
        run: sleep 21600
