name: macOS-Tailscale
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Setting up the Mac
        run: source setup.sh "Aeroniscoolmc2" "" "TAILSCALE_IS_ACTIVE"

      - name: Show Tailscale IP
        run: tailscale ip -4

      - name: Keep Alive
        run: sleep 21600 # This keeps the Mac running for 6 hours
        
